kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 5
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: k8s.gcr.io/spark
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: <NÚCLEOS>
              memory: <MEMORIA RAM>
          volumeMounts:
            - name: nfs
              mountPath: "/FileSystem"
      volumes:
      - name: nfs
        persistentVolumeClaim:
           claimName: oke-fsspvc
           readOnly: false
           
           
           
           
           
           
           

