kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: k8s.gcr.io/spark
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: <NÚCLEOS>
          volumeMounts:
            - name: nfs
              mountPath: "/FileSystem"
       
      volumes:
      - name: nfs
        persistentVolumeClaim:
           claimName: oke-fsspvc
           readOnly: false 
